package Common;

public enum MessageType {
    BAN_USER,
    CREATE_USER,
    LOGIN,
    LOGIN_RESPONSE,
    LOGOUT,
    NOTIFICATION,
    REQUEST_CHATBOX,
    REQUEST_USER_LIST,
    RETURN_CHATBOX,
    RETURN_USER_LIST,
    SEND_MESSAGE,
    UNBAN_USER,
    VIEW_CHATBOX_LOG

}
